### ISSUE TITLE
'next-urql/index.d.ts' is not a module

### ISSUE THREAD

**Issue by tmm** [FormidableLabs/next-urql#1]
Hi there! I'm using TypeScript `3.7.2` (but also tried with `3.6.4`), and am getting the following error.

```
ERROR in /Users/tom/_code/web/pages/login.tsx
6:32 File '/Users/tom/_code/web/node_modules/next-urql/index.d.ts' is not a module.
    4 | import gql from 'graphql-tag'
    5 | import { useMutation } from 'urql'
  > 6 | import { withUrqlClient } from 'next-urql'
```

For context, I was following along with [this tutorial](https://www.howtographql.com/react-urql/0-introduction/), and using Next.js instead of React with React Router.

Happy to provide more info!

**Comment by parkerziegler** [comment]
👋 Thanks for opening the issue @tmm! I need to clean up what gets published to `npm` and ensure we're including the type defs for the public API. I should be able to get this sorted for you today and have a version out later (0.1.1) that you can pick up to get the changes. Thanks for opening!

**Comment by parkerziegler** [comment]
@tmm sorry it took me a bit longer than expected to get this released. Can you give [v0.1.1](https://github.com/FormidableLabs/next-urql/releases/tag/v0.1.1) a try and see if it works for you?
