### ISSUE TITLE
Best Practice to access urqlClient in getInitialProps

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/next-urql#14]
I am wondering what would be the best practice to access the urqlClient in a getInitialProps? Without next-urql I inject the urqlClient into the ctx, but that doesn't seem to happen with next-urql

**Comment by parkerziegler** [comment]
I suppose an easy way for us to do this may be to have `next-urql` attach the `urqlClient` to `ctx`, which is what the [`with-apollo` example](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/apollo.js#L47) over in the Next repo does. In that way I believe you could access `ctx.urqlClient` in your Page component's `getInitialProps` function. Does that sound like an alright solution? I don't yet foresee any issues with this, but if others see a clear flaw please speak up!

**Comment by BjoernRave** [comment]
yea, that sounds like the best option to me, that's what I am doing right now without next-urql as well
