### ISSUE TITLE
Update examples to use TypeScript.

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/next-urql#18]
As more people come to depend on `next-urql`, we want to ensure our types are as correct as possible, and that we're covering as many edge cases as possible in tests and examples. To that end, I think it makes sense to have our `examples` implemented in TypeScript. This hopefully shouldn't be too difficult, following the instructions [here](https://nextjs.org/docs/basic-features/typescript). We should do both `examples/1-with-urql-client` and `examples/2-with-_app.js`.

**Comment by 0xRAG** [comment]
Completed in https://github.com/FormidableLabs/next-urql/commit/5ab88f92507d76af41af0fc3cca3f4d0af74dfdb and https://github.com/FormidableLabs/next-urql/commit/7294a67a634b6e0bbbd73aa47322aa30075cdaff
