### ISSUE TITLE
Usage Questions 

### ISSUE THREAD

**Issue by ivan-kleshnin** [FormidableLabs/next-urql#23]
*My hat is off to your effort guys to make this work without a finalized Suspense!
Still I'm afraid I'm kinda lost in all the different hacks required for all this to run...* 😞  

I'm trying to adopt URQL to my GraphQL + NextJS app and I have a couple of lurking questions.
I've read that I don't need `getInitialProps` to use URQL with NextJS. Sounds great. But I'm not sure how should I restructure my usage patterns previously relying on that function.

Official examples do not demonstrate that aspects.

```js
// pages/[lang]/page.js
function Page(???) {
  // 1) How to pass `ctx` from below to here?
  //    for example I need to log ctx.req.headers

  // 2) How to access NextJS dynamic params (that [lang])?
  //    I previously used getInitialProps({query}) for that

  // 3) What arguments Page accepts in general?
  //    I see that the first is urqlClient, not sure about the others
}

export default withUrqlClient(ctx => {
  return {
    url: `http://localhost:3000/api/graphql`,
     fetchOptions: {
       headers: {
         Authorization: `Bearer ${ctx.req.headers.authorization}`,
       },
     },
  }
})(Page)
```

P.S. If there's a different place to ask questions like this (Slack?) – pls. suggest it.

**Comment by parkerziegler** [comment]
👋 Hey @ivan-kleshnin. Definitely get your confusion here – it's a tricky set of things we do to make this work.

The good thing to note is that `Page` can still implement its own `getInitialProps` method. When wrapping a component with `withUrqlClient`, that HoC will check if `Page` has a `getInitialProps` method and, if so, call it: https://github.com/FormidableLabs/next-urql/blob/master/src/with-urql-client.tsx#L91-L95 So your strategies from questions 1 and 2 I believe should still work just by implementing `Page.getInitialProps`.

In terms of what `Page` receives, it does get the `urqlClient` as a prop, and then anything else a parent component or another HoC passed to it. Basically, it functions like any other HoC where it doesn't touch the props passed by the parent (those get forwarded along), but it does _add_ `urqlClient` such that you could access it lower in the tree if you wanted to.

Does that help answer your questions? You can also ask for help in our [Spectrum channel!](https://spectrum.chat/urql?tab=posts)

**Comment by ivan-kleshnin** [comment]
Thank you. I think there should be a way to entirely drop "getInitialProps" approach. 
Static functions don't go well with hooks and the rest of typical React code. Non-DRY fetching is one of the problems. And adding statics only to capture some params seems hacky to me.

Can't the library pass the original `ctx` along with the `query` by the same manner it passes `urqlClient` to the page of interest?

**Comment by parkerziegler** [comment]
Nope, we can't forward `ctx` along because it would result in a circular structure: https://github.com/zeit/next.js/issues/7371 which Next can't serialize. We actually attempted to before we were aware of this constraint, which promptly broke everything 😅 

In terms of accessing a dynamic parameter, can you use `useRouter` for that? The docs on Dynamic Routing in Next seem to show this approach: https://nextjs.org/docs/routing/dynamic-routes

**Comment by ivan-kleshnin** [comment]
Got it, thank you for the explanations!
