### ISSUE TITLE
Update withUrqlClient typings to reference new NextUrqlClientConfig type

### ISSUE THREAD

**Issue by kylealwyn** [FormidableLabs/next-urql#8]
Most recent changes look great but TS is now complaining given it's not using the updated type: https://github.com/FormidableLabs/next-urql/pull/7/files#diff-b52768974e6bc0faccb7d4b75b162c99R26

**Comment by parkerziegler** [comment]
Released in [v0.2.2](https://github.com/FormidableLabs/next-urql/releases/tag/v0.2.2). Thanks again so much for contributing!
